name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc-14
            cpp_compiler: g++-14
            extra_cxx_flags: ""
            extra_linker_flags: ""

          - os: macos-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++
            extra_cxx_flags: ""
            extra_linker_flags: ""

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtest-dev \
            gcc-14 \
            g++-14

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install googletest

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake
          -B "${{ steps.strings.outputs.build-output-dir }}"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_CXX_STANDARD=23
          -DCMAKE_CXX_STANDARD_REQUIRED=ON
          -DCMAKE_CXX_FLAGS="${{ matrix.extra_cxx_flags }}"
          -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.extra_linker_flags }}"
          -S "${{ github.workspace }}"

      - name: Build
        run: >
          cmake --build
          "${{ steps.strings.outputs.build-output-dir }}"
          --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: >
          ctest
          --build-config ${{ matrix.build_type }}
          --output-on-failure
